# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 273)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setObjectName("labelName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelName)
        self.lineEditName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditName.setObjectName("lineEditName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditName)
        self.labelRoasting = QtWidgets.QLabel(self.centralwidget)
        self.labelRoasting.setObjectName("labelRoasting")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelRoasting)
        self.lineEditRoasting = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditRoasting.setObjectName("lineEditRoasting")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditRoasting)
        self.labelGround = QtWidgets.QLabel(self.centralwidget)
        self.labelGround.setObjectName("labelGround")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelGround)
        self.checkBoxGround = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxGround.setText("")
        self.checkBoxGround.setObjectName("checkBoxGround")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBoxGround)
        self.labelDescribing = QtWidgets.QLabel(self.centralwidget)
        self.labelDescribing.setObjectName("labelDescribing")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelDescribing)
        self.lineEditDescribing = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDescribing.setObjectName("lineEditDescribing")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditDescribing)
        self.labelCost = QtWidgets.QLabel(self.centralwidget)
        self.labelCost.setObjectName("labelCost")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelCost)
        self.lineEditCost = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCost.setObjectName("lineEditCost")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditCost)
        self.labelVolume = QtWidgets.QLabel(self.centralwidget)
        self.labelVolume.setObjectName("labelVolume")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelVolume)
        self.lineEditVolume = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditVolume.setObjectName("lineEditVolume")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEditVolume)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButtonSave = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.verticalLayout.addWidget(self.pushButtonSave)
        self.labelStatus = QtWidgets.QLabel(self.centralwidget)
        self.labelStatus.setText("")
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Капучино"))
        self.labelName.setText(_translate("MainWindow", "Название сорта"))
        self.labelRoasting.setText(_translate("MainWindow", "Степень обжарки"))
        self.labelGround.setText(_translate("MainWindow", "Молотый/в зернах"))
        self.labelDescribing.setText(_translate("MainWindow", "Описание вкуса"))
        self.labelCost.setText(_translate("MainWindow", "Цена"))
        self.labelVolume.setText(_translate("MainWindow", "Обьем упаковки"))
        self.pushButtonSave.setText(_translate("MainWindow", "Сохранить"))
